# Generated by Django 3.1.3 on 2020-11-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=20)),
                ('visitTimes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('address', models.CharField(max_length=40)),
                ('pageID', models.CharField(max_length=20)),
                ('pageURL', models.CharField(max_length=200)),
            ],
        ),
    ]
